name: foodieyou
description: Food Delivery App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.12
  dots_indicator: ^2.1.0
  hexcolor: ^2.0.6
  get: ^4.6.5
  pin_code_fields: 7.4.0
  auto_size_text: ^3.0.0
  bottom_navy_bar: ^6.0.0
  flutter_rating_bar: ^4.0.1
  cloud_firestore: ^4.1.0
  carousel_slider: ^4.2.0
  firebase_auth: ^4.2.0
  firebase_core: ^2.7.0
  shimmer: ^2.0.0
  image_picker: ^0.8.6
  firebase_storage: ^11.0.10
  google_maps_flutter: ^2.2.3
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  flutter_typeahead: ^3.1.3
  intl: ^0.18.0
  firebase_messaging: ^14.2.5
  http: ^0.13.5
  google_sign_in: ^6.0.2
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.14
  flutter_stripe: ^9.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo12.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.9.2
#  animated_splash_screen: ^1.3.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/1024.png
  android_12:
    color: "#FC6011"
    image: assets/images/1024.png
  android12: true

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Black.ttf
          weight: 900
        - asset: assets/fonts/Metropolis-Bold.ttf
          weight: 700
        - asset: assets/fonts/Metropolis-Medium.ttf
          weight: 500
        - asset: assets/fonts/Metropolis-Regular.ttf
          weight: 400

